name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: "0 * * * *" # Runs every hour, on the hour
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull in medium posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          readme_path: "./profile/README.wip.md"
          feed_list: "https://medium.com/feed/@lenra_io_dev"
          comment_tag_name: MEDIUM_POST_LIST
      - name: Pull in reddit posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          readme_path: "./profile/README.wip.md"
          feed_list: "http://www.reddit.com/r/lenra/.rss"
          comment_tag_name: REDDIT_POST_LIST
      - name: Pull in Youtube posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          readme_path: "./profile/README.wip.md"
          feed_list: "https://www.youtube.com/feeds/videos.xml?channel_id=UCsfPy59R3PTcFWtPO-Yklrw"
          comment_tag_name: YOUTUBE_VIDEO_LIST
